version: '3'
services:
  app:
    build: .
    ports:
      - 7070:7070
    volumes:
      - todo-app:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development

volumes:
  todo-app:
